export{default as CapaTemplate} from './CapaTemplate.vue'
export{default as SobreTemplate} from './SobreTemplate.vue'
export{default as ProjetosTemplate} from './ProjetosTemplate.vue'
export{default as SkillsTemplate} from './SkillsTemplate.vue'
export{default as ServicosTemplate} from './ServicosTemplate.vue'
export{default as ContatoTemplate} from './ContatoTemplate.vue'