export{default as Header} from './Header.vue'
export{default as Hero} from './Hero.vue'
export{default as Sobre} from './Sobre.vue'
export{default as Projetos} from './Projetos.vue'
export{default as Skills} from './Skills.vue'